### ISSUE TITLE
Installation on Mac OS Monterey non-functional

### ISSUE THREAD

**Issue by IanFoertsch-clumio** [containerscrew/tftools#1]
Hey @containerscrew -> tftools looks great and I'd love to use it. Unfortunately I'm having trouble with the install on a Mac:

```
$ curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/containerscrew/tftools/main/scripts/install.sh | bash
Downloading... v0.5.0/tftools-darwin-.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```

☝️ I believe this is due to the install script supporting a combination of Darwin/x86_64 here: https://github.com/containerscrew/tftools/blob/main/scripts/install.sh#L58, but it looks like it's available as a release here: https://github.com/containerscrew/tftools/releases/download/v0.5.0/tftools-darwin-amd64.tar.gz.

**Comment by containerscrew** [comment]
Hi @IanFoertsch-clumio, thank you so much for reporting it! I'm glad you like the tool. Let me check what you comment of the missing  https://github.com/containerscrew/tftools/releases/download/v0.5.0/tftools-darwin-amd64.tar.gz package for darwin amd64. 

I will try to give you an answer as soon as possible. I understand that using brew as installation mode also fails you, right?

**Comment by containerscrew** [comment]
If I understand correctly, on OSX amd64 a `uname -m` returns `'x86_64'`, so in the install.sh script I need to change this https://github.com/containerscrew/tftools/blob/main/scripts/install.sh#L58 for this 


```
# Check OS
OS=$(uname -s)
arch=$(uname -m)
cli_arch=""
case $OS in
  Darwin)
    case $arch in
      x86_64)
        cli_arch="amd64" <<<<---- change here
```

Sorry for not being able to reproduce it, I personally use mac OSX Ventura with arm64 architecture

**Comment by IanFoertsch-clumio** [comment]
Hey @containerscrew, thanks for the rapid response. 😬 I haven't actually tried the brew installation process, but I can give it a try.

Here's the `OS` & `arch` values from my local machine:
```
➜  ~/go/src/tftools git:(fix-missing-arch-for-darwin-amd) ✗ $ uname -m
x86_64
➜  ~/go/src/tftools git:(fix-missing-arch-for-darwin-amd) ✗ $ uname -s
Darwin
```

FWIW This patch file was able to resolve the download issue:
```
From 603dc146cfa716dfbd92beafff6b24cdd1d097d8 Mon Sep 17 00:00:00 2001
From: Ian Foertsch <ian@clumio.com>
Date: Thu, 1 Jun 2023 18:41:26 -0500
Subject: [PATCH] Adds amd64 as an installation candidate in the install script
 for Darwin/AMD systems

---
 scripts/install.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/scripts/install.sh b/scripts/install.sh
index 6474c34..e63b85f 100644
--- a/scripts/install.sh
+++ b/scripts/install.sh
@@ -55,7 +55,7 @@ case $OS in
   Darwin)
     case $arch in
       x86_64)
-        cli_arch=""
+        cli_arch=amd64
         ;;
       arm64)
         cli_arch=$arch
--
2.39.1
```

**Comment by containerscrew** [comment]
Thanks for the report! Fixed then in my master branch! Hope you enjoy.
