### ISSUE TITLE
Can't install specific release

### ISSUE THREAD

**Issue by ansromanov** [containerscrew/tftools#8]
When I tried to setup specific version from readme, I got the following error:

```
curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/containerscrew/tftools/main/scripts/install.sh | sh "v0.8.0" 
sh: v0.8.0: No such file or directory
```

It was reproducible in Mac OS (zsh) and docker builds (ubuntu).

I propose to add support for environment variable to choose correct version, like 

```
curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/containerscrew/tftools/main/scripts/install.sh | VERSION="v0.9.0" sh
```

**Comment by ansromanov** [comment]
I checked that following code work 

```
curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/containerscrew/tftools/main/scripts/install.sh | sh -s -- -v "$TFTOOLS_VERSION"
```

According to https://github.com/containerscrew/infratools/blob/v1.9.0/Containerfile#L65

**Comment by containerscrew** [comment]
Hi @ansromanov ,

It seems that the README doc is out of date. Indeed the curl you attach from the Containerfile (https://github.com/containerscrew/infratools/blob/v1.9.0/Containerfile#L65) of my other infratools repo, is the correct one. I will update the doc!

The good one is this:

Example:
https://raw.githubusercontent.com/containerscrew/tftools/main/scripts/install.sh | sh -s -- -v "v0.8.0"

Is this correct?

Thanks for reporting it!

**Comment by ansromanov** [comment]
Yes, it works for me.
